### ISSUE TITLE
Startup: error at the migration phase

### ISSUE THREAD

**Issue by Disti4ct** [mynearwallet/confidant-client#3]
Error:
`ERROR: read ECONNRESET`

Commands before error:
> There are not visual problems with dependency instalation or with dowloading a Postgres image

![error](https://user-images.githubusercontent.com/61930014/200252758-a5c61d51-6830-45b6-8d7b-020714584211.png)

**Comment by lapkoshka** [comment]
@NotEternal Wrong repo
